set tabstop=4       " number of visual spaces per TAB
set softtabstop=4   " number of spaces in tab when editing
set expandtab       " tabs are spaces

set showcmd         " show command in bottom bar

set incsearch       " search as characters are entered
set hlsearch        " highlight matches
syntax on

